### ISSUE TITLE
is it no longer working? currently updated to world 4 update

### ISSUE THREAD

**Issue by abdullzz** [Touch-Portal-MSFS/MSFSTouchPortalPlugin#34]
i was doing just fine yesterday. i even make my own buttons. but today TP just wont connect to my MSFS. the current status for the connection is just always false. any fix for this?

**Comment by tlewis17** [comment]
Make sure you are using the 0.5.3 that was released a week and a half ago. I just tested it today with the MSFS update and TP updates and it is working.

**Comment by p4cm4n** [comment]
It worked for me this weekend with 0.5.3

**Comment by abdullzz** [comment]
> Make sure you are using the 0.5.3 that was released a week and a half ago. I just tested it today with the MSFS update and TP updates and it is working.

i already import it with 0.5.3, its not working at all
